### ISSUE TITLE
Stranger airlocks don't account for the auto angle snapping, and door states aren't synced on join

### ISSUE THREAD

**Issue by misternebula** [qsb-dev/quantum-space-buddies#521]
![image](https://user-images.githubusercontent.com/41904486/167266126-0b2fcfb6-859e-4636-981a-ddb8e7187fd7.png)

**Comment by JohnCorby** [comment]
i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc i hate the dlc

**Comment by misternebula** [comment]
Partially fixed.
