### ISSUE TITLE
Ship falls through QM sometimes when not there.

### ISSUE THREAD

**Issue by misternebula** [qsb-dev/quantum-space-buddies#598]
Repro steps
- Have the server host fly you both to the QM and land on it's surface.
- Both get out
- As the client, fly up out of the QM. Then fly back down onto the QM.
- The ship will have glitched into terrain/fallen through the floor for the client, but still be in the correct place for the server host.

**Comment by JohnCorby** [comment]
this is because the qm faces the client and the ship is parented to the qm in qsb so instead of hitting the ship like a tennis ball it just moves the ship with it.

people rarely leave the qm without the ship so this is rare enough to not care about
