### ISSUE TITLE
OPEN TO MULTIPLAYER，but  not displaying User ID！

### ISSUE THREAD

**Issue by clearlove998** [qsb-dev/quantum-space-buddies#644]
**Describe the bug**
OPEN TO MULTIPLAYER，but  not displaying User ID！

**Screenshots**
![1692234617770](https://github.com/misternebula/quantum-space-buddies/assets/92611762/49f26254-885b-4319-9873-ae5e27c7e881)

**Please complete the following information:**
 - OS :Windows
 - Outer Wilds version :latest
 - Outer Wilds vendor (Steam/Epic) :Steam
 - QSB Version :0.30.2
![1692234983630](https://github.com/misternebula/quantum-space-buddies/assets/92611762/3d046644-0164-45d8-9ed5-249b94610bb1)

**Comment by misternebula** [comment]
I can't replicate this - does this still happen?
