### ISSUE TITLE
Mod unable to start, no multiplayer options available in main menu

### ISSUE THREAD

**Issue by FenryswoIf** [qsb-dev/quantum-space-buddies#648]
OS: Windows 10
Outer Wilds Version: 1.14
Outer Wilds Vendor: Epic
QSB Version: 31.1

After getting the latest version of QSB and the OWML, the mod seems to be unable to launch. The game starts, but the logs of the modloader show an unknown error message (see below) and the main menu lacks the options to Connect and to Host a multiplayer game. 
The game was last played with the QSB version 30.2, everything working as intended

Note: When starting the game with QSB 30.2 now, the missing multiplayer options reappear. However choosing Host a Multiplayer game won't work.

--

> **OWML** | Initializing enum creator

> **OWML** | TypeLoadException: Could not resolve type with token 01000061 (from typeref, class/assembly Steamworks.Packsize, com.rlabrecque.steamworks.net, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)Stacktrace: UnityEngine.GameObject:AddComponent(Type)OWML.Abstractions.GameObjectHelper:CreateAndAdd(Type, String)OWML.ModLoader.Owo:InitializeMod(Type, IModHelper)OWML.ModLoader.Owo:LoadMods()OWML.ModLoader.ModLoader:LoadMods()PermanentManager:Awake()_

![image](https://github.com/qsb-dev/quantum-space-buddies/assets/148070665/86e81bd2-0827-41d1-8258-7b20c8fcf53c)

**Comment by misternebula** [comment]
Fixed in latest version
