### ISSUE TITLE
QM tower stops moving when it reaches 6th location

### ISSUE THREAD

**Issue by JohnCorby** [qsb-dev/quantum-space-buddies#667]
there have been multiple reports that having 2+ people in the tower will make it break randomly.

one of them said that causing it was as simple as turning the flashlight on and off a few times. i dont know if this is reproduceable locally.

fortunately, this can be worked around by simply only having one person in the quantum moon at a time, but thats obviously not ideal

UPDATE: appears to break specifically when passing thru 6th location. this is either when ur outside or inside.

**Comment by misternebula** [comment]
confirmed in latest version, just visting the 6th location causes the shrine to no longer change the QM's state - not even just at the north pole
