### ISSUE TITLE
Is it possible to have higher FPS when playing Quantum Space Buddies?

### ISSUE THREAD

**Issue by lmills87** [qsb-dev/quantum-space-buddies#673]
I'm aware of the secretsettings.txt fix to increase the frame rate, but regardless of what I set it to it seems to have no effect. Is it possible to have a higher frame rate when playing this mod?

**Comment by JohnCorby** [comment]
presumbly an issue for [this](https://discord.com/channels/929708786027999262/1229256466440130702). this is not qsb's fault
