### ISSUE TITLE
change KCP port

### ISSUE THREAD

**Issue by ZohZie** [qsb-dev/quantum-space-buddies#691]
is it possible to change the port that is used?

i have something else on 7777, and it wont let me cnage it in my routers settings.

would be so much easier to just be able to change which port this used, cheers!

**Comment by JohnCorby** [comment]
you could also just not use KCP (use the steam networking thing instead), unless thats not working for you

**Comment by ZohZie** [comment]
Unfortunately it's not from steam

**Comment by JohnCorby** [comment]
You dont need the game on steam to play on steam
